const ACTIONS={
    LOGIN:'LOGIN',
    GET_TOKEN:'GET_TOKEN',
    GET_USER:'GET_USER',
    ADD_TO_CART:' ADD_TO_CART',
    REMOVE_FROM_CART:' REMOVE_FROM_CART',
    ADJUST_QTY:'ADJUST_QTY',
    LOAD_CURRENT_ITEM:'LOAD_CURRENT_ITEM',
}
//  ADD_TO_CART = "ADD_TO_CART";
//  ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
//  REMOVE_FROM_CART = "REMOVE_FROM_CART";
//  LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export default ACTIONS